export enum MESSAGE {
  SEND_MESSAGE = "SEND_MESSAGE",
}

export enum AGENT {
  GET_AGENTS = "GET_AGENTS",
}

export enum BALANCE {
  GET_BALANCE = "GET_BALANCE",
}

export enum TRANSACTION {
  GET_TRANSACTIONS = "GET_TRANSACTIONS",
}
